[ req ]
default_bits        = 4096
default_md          = sha256
prompt              = no

x509_extensions     = v3_spiffe_root

distinguished_name = req_distinguished_name
x509_extensions = v3_ca, v3_spiffe_root

[req_distinguished_name]
commonName = "Consul Mesh Root CA"
#commonName = pri-abc1234.vault.ca.803fc394.consul

[v3_ca]
# Standard CA extensions
basicConstraints = critical, CA:TRUE
keyUsage = critical, keyCertSign

[v3_svid]
# Extensions for a leaf SVID
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
# This is the crucial SPIFFE part
#subjectAltName = URI:spiffe://803fc394-02d6-c2b6-d1cd-27adf5062aea.consul
