[req]
default_bits        = 4096
default_md          = sha256
prompt              = no
distinguished_name  = dn
req_extensions      = v3_intermediate_req
distinguished_name  = req_distinguished_name

[ ca ]
default_ca = CA_default

[ CA_default ]
dir               = ./
certs             = $dir/certs
new_certs_dir     = $dir/newcerts
database          = $dir/index.txt
serial            = $dir/serial
private_key       = $dir/certs/ca.key
certificate       = $dir/certs/ca.crt
policy            = policy_anything

[ policy_anything ]
countryName             = optional
stateOrProvinceName     = optional
localityName            = optional
organizationName        = optional
organizationalUnitName  = optional
commonName              = optional
emailAddress            = optional

[req_distinguished_name]
commonName = "Consul Mesh Intermediate CA"

# [v3_ca]
# # Standard CA extensions
# basicConstraints = critical, CA:TRUE
# keyUsage = critical, digitalSignature, keyCertSign

[ v3_intermediate_req ]
basicConstraints = critical, CA:true, pathlen:1
keyUsage         = critical, keyCertSign, cRLSign
subjectKeyIdentifier = hash
### Testing without the spiffe URI for now, as it may not be needed on the intermediate CA
# subjectAltName = URI:spiffe://803fc394-02d6-c2b6-d1cd-27adf5062aea.consul






### Historical attempts ### 
# [v3_svid]
# # Extensions for a leaf SVID
# basicConstraints = critical, CA:FALSE
# keyUsage = critical, digitalSignature, keyEncipherment, keyCertSign
# # This is the crucial SPIFFE part
# subjectAltName = URI:spiffe://803fc394-02d6-c2b6-d1cd-27adf5062aea.consul

# # [v3_intermediate]
# # # Basic constraints for an intermediate CA
# # basicConstraints = critical, CA:TRUE, pathlen:0
# # keyUsage = CertSign, CRLSign
# # subjectKeyIdentifier = hash
# # authorityKeyIdentifier = keyid:always,issuer

# # [ v3_intermediate_ca ]
# # subjectKeyIdentifier = hash
# # authorityKeyIdentifier = keyid:always,issuer
# # basicConstraints = critical, CA:true, pathlen:0
# # keyUsage = critical, digitalSignature, CRLSign, keyCertSign
